baseURL = "https://www.bartholomy.ooo/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "bartholomy"
theme = "bth-hermit"

# googleAnalytics = "UA-123-45"
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "© hautogdoad" # This message is only used by the RSS template.

# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true


[author]
  name = "Bartholomy"
  url = "about"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 80
[[related.indices]]
  name = 'date'
  weight = 10

[params]
  homeSubtitle = "Unlimited Human Renaissance"
  footerCopyright = 'hautogdoad'
  logo = "headshot.png"
  logolink = "about"
  favicon = 'covers/0166.elites.png'
  subscribeURL = "https://www.tinyletter.com/bartholomy"

  featuredPost = 'posts/12.narrative_consciousness.md'

  relatedPosts = true  # Add a related content section to all single posts page
  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006.01.02"
  dateformNumYearMon = "2006.01"
  dateformNumTime = "2006.01.02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Neuroscience, psychoanalysis, anthropology, philosophy, and moral critique"
  images = ["headshot.png", "covers/0152.witch_hunt.jpg"]

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]
  # bgImg = ""  # Homepage background-image URL

[menu]

  [[menu.main]]
    name = "posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "books"
    url = "books/"
    weight = 20

  [[menu.main]]
    name = "music"
    url = "music/"
    weight = 30

  [[menu.main]]
    name = "about"
    url = "about/"
    weight = 40
