baseURL = "https://www.bartholomy.ooo/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "bartholomy"
theme = "bth-hermit"

# googleAnalytics = "UA-123-45"
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "© hautogdoad" # This message is only used by the RSS template.


[author]
  name = "Bartholomy"
  url = "about"

[params]
  # if the post is draft: true, this will currently not break the build, but it won't show up in posts/
  featuredPost = 'posts/12.narrative_consciousness.md'

  # essential settings
  homeSubtitle = "Unlimited Human Renaissance"
  footerCopyright = 'hautogdoad'
  logo = "headshot.png"
  logolink = "about"
  favicon = "headshot-zoom.ico"
  subscribeURL = "https://www.tinyletter.com/bartholomy"
  relatedPosts = true  # Add a related content section to all single posts page
  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  # dates
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006.01.02"
  dateformNumYearMon = "2006.01"
  dateformNumTime = "2006.01.02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Moral critique, neuroscience, psychoanalysis, anthropology, and philosophy."
  images = ["headshot.png", "covers/0152.witch_hunt.jpg"]

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]
  # bgImg = ""  # Homepage background-image URL


[taxonomies]
  tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 80
[[related.indices]]
  name = 'date'
  weight = 10


[menu]
  [[menu.main]]
    name = "posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "books"
    url = "books/"
    weight = 20

  [[menu.main]]
    name = "music"
    url = "music/"
    weight = 30

  [[menu.main]]
    name = "about"
    url = "about/"
    weight = 40


[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true

# failing, but this is kinda bleeding edge, so that may be it
[markup.goldmark.extensions.typographer]
# double dash -- makes mdash:
enDash = '&mdash;'

# maybe:
# ellipsis = '...'

# I don't like smart quotes:
leftDoubleQuote = '"'
rightDoubleQuote = '"'

# german style:
# leftDoubleQuote = '&bdquo;'
# rightDoubleQuote = '&rdquo;'

##########
# defaults:
# apostrophe = '&rsquo;'
# ellipsis = '&hellip;'
# emDash = '&mdash;'
# enDash = '&ndash;'

# leftAngleQuote = '&laquo;'
# leftDoubleQuote = '&ldquo;'
# leftSingleQuote = '&lsquo;'

# rightAngleQuote = '&raquo;'
# rightDoubleQuote = '&rdquo;'
# rightSingleQuote = '&rsquo;'

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
wrapStandAloneImageWithinParagraph = true

[markup.goldmark.parser.attribute]
block = false
title = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false
