baseURL = "https://www.bartholomy.ooo"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "bartholomy"
theme = "bth-hermit"

# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "© hautogdoad" # This message is only used by the RSS template.

# googleAnalytics = "UA-123-45"

[author]
  name = "Bartholomy"
  url = "about"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  # hack! this sets the "plural" of tag:
  # just so I don't have to define my own layouts/_default/series.html I guess
  # https://www.kiroule.com/article/add-series-taxonomy-to-hugo-theme/
  # tag = 'series'

  # or maybe I can live with this:
  tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'series'
  weight = 100
[[related.indices]]
  name = 'categories'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 80


[params]
  homeSubtitle = "Unlimited Human Renaissance"
  footerCopyright = 'hautogdoad'
  logo = "headshot.png"
  logolink = "about"
  favicon = 'covers/0166.elites.png'
  subscribeURL = "https://www.tinyletter.com/bartholomy"

  # featuredPost = 'posts/32.nietzschean_pedagogy.md'
  featuredPost = 'posts/12.narrative_consciousness.md'

  relatedPosts = true  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006.01.02"
  dateformNumYearMon = "2006.01"
  dateformNumTime = "2006.01.02 15:04 -0700"

  # Metadata mostly used in document's head
  # opengraph?
  description = "Neuroscience, psychoanalysis, anthropology, philosophy, and moral critique"
  # images = [""]

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]
  # bgImg = ""  # Homepage background-image URL

[menu]

  [[menu.main]]
    name = "posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "books"
    url = "books/"
    weight = 20

  [[menu.main]]
    name = "music"
    url = "music/"
    weight = 30

  [[menu.main]]
    name = "about"
    url = "about/"
    weight = 40
