baseURL = "https://www.bartholomy.ooo/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "bartholomy"
theme = "bth-hermit"

# use &#169; {{ now.Format "2006" }} preceeding:
copyright = "hautogdoad"

googleAnalytics = "G-CXJ7N79PMM"

# no effect in my custom rss template, currently.
# rssLimit = 10  # Maximum number of items in the RSS feed.

# Keep images in assets/ now, so that I can load them with resources.Get, and
# then access .MediaType etc. By extending the static dir like this, I can
# access images in any doc with plain markdown, as though it were loaded into
# the static dir.
staticDir = ['static', 'assets']

[params.author]
  name = "Bartholomy"
  url = "/about"
  email = "yo@bartholomy.ooo"

[params]
  # NOTE: .Site.GetPage needs filename, not slug:
  # if the post is draft: true, this will currently not break the build, but it won't show up in posts/
  featuredPost = 'posts/325.experience.md'

  # meta stuff
  homeSubtitle = "Unlimited Human Renaissance"
  # NOTE: meta tags: .Description before .Summary before .Site.Description
  # .Page.Params.Description := description without subtitle
  # .Page.Params.Summary := description as subtitle
  description = "Moral critique, neuroscience, psychoanalysis, anthropology, and philosophy."
  themeColor = "#c65108"
  favicon = "headshot-zoom.ico"
  images = ["headshot.png", "covers/0152.witch_hunt.jpg"]

  # footer
  logo = "headshot_150px.png"
  logolink = "/about"
  copyrightlink = "/about/privacy/"
  defaultPlace = "Fool's Bluff, Nevada"
  defaultStudyButton = "study with bartholomy"

  # flags
  code_copy_button = false

  # dates
  dateformNum     = "2006.01.02"
  dateformRFC822 = "Mon, 02 Jan 2006 15:04:05 -0700"

[taxonomies]
  tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 80
[[related.indices]]
  name = 'date'
  weight = 10

[menu]
  [[menu.main]]
    name = "posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "books"
    url = "books/"
    weight = 20

  [[menu.main]]
    name = "music"
    url = "music/"
    weight = 30

  [[menu.main]]
    name = "study"
    url = "study/"
    weight = 30

  [[menu.main]]
    name = "about"
    url = "about/"
    weight = 40

  # nested list for reference should I need it:
  # parent = ""
  # https://gohugo.io/content-management/menus/#example-site-configuration
  # [[menu.main]]
  #   name = "support"
  #   url = "support/"
  #   parent = "about"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true

# failing, but this is kinda bleeding edge, so that may be it
[markup.goldmark.extensions.typographer]
# double dash -- makes mdash:
enDash = '&mdash;'

# no collapsed &hellip;
ellipsis = '...'

# I don't like smart quotes:
rightDoubleQuote = '"'
rightSingleQuote = "'"
rightAngleQuote = "'"
leftDoubleQuote = '"'
leftSingleQuote = "'"
leftAngleQuote = "'"
apostrophe = "'"

# german style:
# leftDoubleQuote = '&bdquo;'
# rightDoubleQuote = '&rdquo;'

##########
# defaults:
# apostrophe = '&rsquo;'
# ellipsis = '&hellip;'
# emDash = '&mdash;'
# enDash = '&ndash;'

# leftAngleQuote = '&laquo;'
# leftDoubleQuote = '&ldquo;'
# leftSingleQuote = '&lsquo;'

# rightAngleQuote = '&raquo;'
# rightDoubleQuote = '&rdquo;'
# rightSingleQuote = '&rsquo;'

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
wrapStandAloneImageWithinParagraph = true

[markup.goldmark.parser.attribute]
block = false
title = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false

# https://gohugo.io/getting-started/configuration-markup/#highlight
[markup.highlight]
style = 'gruvbox'
