[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.111.3"

[context.deploy-preview]
  # HUGO_BASEURL = "/"
  # FIXME: get rid of the -D flag here once I get this figured out:
  command = "hugo -D --gc --minify -b master--taupe-frangipane-7e40dd.netlify.app"

[context.branch-deploy]
  # HUGO_BASEURL = "/"
  command = "hugo -D --gc --minify -b draft--taupe-frangipane-7e40dd.netlify.app"
